apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: "spark-upgraded"
helmCharts:
- name: spark
  repo: https://charts.bitnami.com/bitnami/
  releaseName: upgraded
  namespace: spark-upgraded
  valuesInline:
    worker:
      replicaCount: 1
    ingress:
      enabled: true
      pathType: ImplementationSpecific
      hostname: spark-upgraded.test
      ingressClassName: nginx


