apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
- name: spark
  repo: https://charts.bitnami.com/bitnami/
  version: 6.1.10
  releaseName: dev
  namespace: spark
  valuesInline:
    worker:
      replicaCount: 1
    ingress:
      enabled: true
      pathType: ImplementationSpecific
      hostname: spark-dev.test
      ingressClassName: nginx

